### ISSUE TITLE
Can we get an example of how to do a plugin with string and struct parameters?

### ISSUE THREAD

**Issue by justinmchase** [denosaurs/plug#9]

**Comment by brandonros** [comment]
probably related to https://github.com/denosaurs/plug/issues/10

**Comment by brandonros** [comment]
https://github.com/denosaurs/plug/pull/11

**Comment by eliassjogreen** [comment]
This is not directly related to plug as it is simply the dylib loader, examples and other ffi or related projects can be found:
* https://github.com/denoland/deno/tree/main/test_ffi 
* https://github.com/DjDeveloperr/deno_gl
* https://github.com/denodrivers/sqlite3
* https://github.com/denosaurs/byte_type/blob/main/ffi.ts

**Comment by wobsoriano** [comment]
I do it like this for now

```ts
const encoder = new TextEncoder();

function encode(value: string) {
  return encoder.encode(value + "\0");
}

const dylib = Deno.dlopen("./path/to/lib.so", {
  "getVersion": {
    name: 'GetVersion',
    parameters: ["pointer"],
    result: "pointer",
  }
})

const pointer = dylib.symbols.getVersion(
  encode("Some string")
)

const value = new Deno.UnsafePointerView(pointer).getCString()

// value is now a string
```

**Comment by brandonros** [comment]
what about a struct?

**Comment by wobsoriano** [comment]
Didn't know denosaurs have a good module for this

```ts
import { Struct, i32le } from "https://deno.land/x/byte_type@0.1.7/mod.ts"

const _lib = Deno.dlopen("app.so", {
  add: { parameters: ["pointer"], result: "i32" }
});

const i32 = i32le
const struct = new Struct({ a: i32, b: i32 })

function add(a0: {a: number; b: number }) {
  const _buf_a0 = new Uint8Array(_Input.size)
  const _view_a0 = new DataView(_buf_a0.buffer)
  _Input.write(_view_a0, 0, a0)
  const _result = sys.symbols.add(_buf_a0)
  return _result as number
}

add({
  a: 6,
  b: 9
})
```

**Comment by brandonros** [comment]
nice

if you want to go for gold i’d show how to do FFI with a function that returns a pointer to a struct or how to reference a struct that was passed as a pointer (aka if the FFI call modified the struct and it’s Deno’s turn to read the changes back)

**Comment by wobsoriano** [comment]
> nice
> 
> if you want to go for gold i’d show how to do FFI with a function that returns a pointer to a struct or how to reference a struct that was passed as a pointer (aka if the FFI call modified the struct and it’s Deno’s turn to read the changes back)

I think this can all be done in that module. It’s just missing docs

**Comment by justinmchase** [comment]
What is `_Input` in that example? Seems to not be in the example.

**Comment by wobsoriano** [comment]
> What is `_Input` in that example? Seems to not be in the example.

fixed

**Comment by wobsoriano** [comment]
I am not sure how to read structs yet with [byte_type](https://deno.land/x/byte_type@0.1.7/mod.ts). Only writing.
